sudo: false
language: node_js
node_js:
  - '10.0.0'
before_install:
  - npm i -g npm@6.4.1
  - npm install -g typescript
stages:
  - test
  - name: deploy
    if: (NOT type IN (pull_request)) AND (branch = demo)
jobs:
  include:
    - stage: test
      name: "Lint and Test"
      script:
        - npm run lint
        - npm run test
    - stage: deploy    
      name: "Deploy to NPM"
      script:
        - npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script: 
          - ./scripts/publish.sh
        on:
          branch: demo
